### ISSUE TITLE
Missing setCustomNameStandardization function

### ISSUE THREAD

**Issue by akasakakona** [mparticle-integrations/mparticle-javascript-integration-google-analytics-4#54]
When running this line:
https://github.com/mparticle-integrations/mparticle-javascript-integration-google-analytics-4/blob/8fc26c2f2427c34cfcd787fbb7d856d821ddd0da/packages/GA4Client/dist/GoogleAnalytics4EventForwarderClientSide-Kit.common.js#L140

The browser throws this error. 
<img width="463" alt="image" src="https://github.com/mparticle-integrations/mparticle-javascript-integration-google-analytics-4/assets/43999515/e03a365d-4ffe-45a1-8f27-d7d821b7acf4">

**Comment by v-mamaya** [comment]
Hey, would you mind raising a [ticket](https://support.mparticle.com/hc/en-us/requests/new) to our support team? I think this is a configuration problem, not an issue. Thank you very much!

**Comment by rmi22186** [comment]
Hi @akasakakona  - This has been released as part of v1.3.1.  If you are using the snippet, you will get this automatically.  If you use npm, please update your package.json for @mparticle/web-google-analytics-4-client-kit for be 1.3.1.

Thanks to @mmustafa-tse for the fix!

I am closing this for now, but please reopen if you have any issues.
